---
- name: 'DOCKER : copy docker env file'
  ansible.builtin.template:
    src: templates/.env.j2
    dest: files/.env
    mode: '0644'

- name: 'DOCKER : create volume'
  community.docker.docker_volume:
    name: volume_pihole
  become: true

- name: 'DOCKER : create containers'
  community.docker.docker_compose_v2:
    project_src: files/
    pull: always
#    recreate: always
    files: '{{ item.files }}'
  loop:
    - { files: docker-compose-pihole.yml }
#    - { files: docker-compose-unbound.yml }
  become: true

- name: 'DOCKER : remove unused images'
  community.docker.docker_prune:
    images: true
  become: true
